package gui.handlers;

import javax.swing.*;
import java.awt.event.*;

/**
 * handles the events generated by comboboxes for the item attributes
 */
public class AttributeComboBoxHandler implements ActionListener {

    private JComboBox<String> sourceComboBox;
    private Setter<String> setter;

    public AttributeComboBoxHandler(JComboBox<String> sourceComboBox, Setter<String> setter) {
        this.sourceComboBox = sourceComboBox;
        this.setter = setter;
    }

    /**
     * Handles the combo box events
     * Cleverly, and conveniently if I am honest, if the custom option is selected, then the textField event handler will
     * overwrite this, as that updates whenever the text box is typed in
     *
     * @param e the event to be processed
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        setter.apply((String) sourceComboBox.getSelectedItem()); // itll work, trust, literally everything is an object (i think)

    }
}
